### ISSUE TITLE
java.lang.UnsatisfiedLinkError: 

### ISSUE THREAD

**Issue by kiran9879** [zfdang/android-multiple-images-selector#32]
at com.facebook.soloader.SoLoader.doLoadLibraryBySoName (SoLoader.java:703)
  at com.facebook.soloader.SoLoader.loadLibraryBySoName (SoLoader.java:564)
  at com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:500)
  at com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:455)
  at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load (ImagePipelineNativeLoader.java:40)

It seems like 32 bit / 64 bit issue. Crashing almost all of my install. It was working fine before. 

Do you have any fix for this?

**Comment by ngcsoft2020** [comment]
Facing same issue #kiran9879

Caused by java.lang.UnsatisfiedLinkError
couldn't find DSO to load: libimagepipeline.so caused by: dlopen failed: library "/system/lib/libimagepipeline.so" needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
com.facebook.soloader.SoLoader.doLoadLibraryBySoName (SoLoader.java:703)
com.facebook.soloader.SoLoader.loadLibraryBySoName (SoLoader.java:564)
com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:500)
com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:455)
com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load (ImagePipelineNativeLoader.java:40)
com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit> (NativeMemoryChunk.java:31)
com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc (NativeMemoryChunkPool.java:25)
com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc (NativeMemoryChunkPool.java:13)
com.facebook.imagepipeline.memory.BasePool.get (BasePool.java:267)
com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream.<init> (MemoryPooledByteBufferOutputStream.java:51)
com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer (MemoryPooledByteBufferFactory.java:73)
com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer (MemoryPooledByteBufferFactory.java:24)
com.facebook.imagepipeline.producers.LocalFetchProducer.getByteBufferBackedEncodedImage (LocalFetchProducer.java:87)
com.facebook.imagepipeline.producers.LocalFetchProducer.getEncodedImage (LocalFetchProducer.java:99)
com.facebook.imagepipeline.producers.LocalFileFetchProducer.getEncodedImage (LocalFileFetchProducer.java:32)
com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult (LocalFetchProducer.java:52)
com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult (LocalFetchProducer.java:48)
com.facebook.common.executors.StatefulRunnable.run (StatefulRunnable.java:43)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
com.facebook.imagepipeline.core.PriorityThreadFactory$1.run (PriorityThreadFactory.java:51)
java.lang.Thread.run (Thread.java:764)

please give any response soon

**Comment by Taimoor-Azam** [comment]
Facing same issue #kiran9879

Caused by java.lang.UnsatisfiedLinkError
couldn't find DSO to load: libimagepipeline.so caused by: dlopen failed: library "/system/lib/libimagepipeline.so" needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
com.facebook.soloader.SoLoader.doLoadLibraryBySoName (SoLoader.java:703)
com.facebook.soloader.SoLoader.loadLibraryBySoName (SoLoader.java:564)
com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:500)
com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:455)
com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load (ImagePipelineNativeLoader.java:40)
com.facebook.imagepipeline.memory.NativeMemoryChunk. (NativeMemoryChunk.java:31)
com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc (NativeMemoryChunkPool.java:25)
com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc (NativeMemoryChunkPool.java:13)
com.facebook.imagepipeline.memory.BasePool.get (BasePool.java:267)
com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream. (MemoryPooledByteBufferOutputStream.java:51)
com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer (MemoryPooledByteBufferFactory.java:73)
com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer (MemoryPooledByteBufferFactory.java:24)
com.facebook.imagepipeline.producers.LocalFetchProducer.getByteBufferBackedEncodedImage (LocalFetchProducer.java:87)
com.facebook.imagepipeline.producers.LocalFetchProducer.getEncodedImage (LocalFetchProducer.java:99)
com.facebook.imagepipeline.producers.LocalFileFetchProducer.getEncodedImage (LocalFileFetchProducer.java:32)
com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult (LocalFetchProducer.java:52)
com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult (LocalFetchProducer.java:48)
com.facebook.common.executors.StatefulRunnable.run (StatefulRunnable.java:43)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
com.facebook.imagepipeline.core.PriorityThreadFactory$1.run (PriorityThreadFactory.java:51)
java.lang.Thread.run (Thread.java:764)

please give any response soon

**Comment by zfdang** [comment]
it seems similar issues have been reported in Fresco. see  https://github.com/facebook/fresco/issues/2381#issuecomment-516825599
